# AI 配置
ai:
  model: deepseek
  api_key: "your_api_key_here"
  temperature: 0.7
  max_tokens: 3000
  
# 输出配置
output:
  format:
    markdown:
      enabled: true
      template: "templates/markdown_template.md"
      toc: true  # 是否生成目录
      code_highlight: true  # 是否启用代码高亮
    
    mindmap:
      enabled: true
      template: "templates/mindmap_template.md"
      max_depth: 3  # 最大层级深度
      include_examples: true  # 是否包含示例
    
    summary:
      enabled: true
      template: "templates/summary_template.md"
      max_length: 3000
      min_length: 500
      
# 处理配置
processing:
  subtitle:
    engine: "whisper"  # whisper 或 subtitleedit
    language: "zh"  # 语言代码
    quality: "high"  # 质量设置
    
  content:
    # 内容处理选项
    merge_short_paragraphs: true  # 合并短段落
    remove_timestamps: true  # 删除时间戳
    clean_special_chars: true  # 清理特殊字符
    
  highlight:
    # 重点提取设置
    keywords: ["重点", "注意", "记住", "考试", "重要"]
    mark_style: "bold"  # bold 或 highlight
    
# 文件路径
paths:
  input: "./input"
  output: "./output"
  temp: "./temp"
  logs: "./logs"
  
# 模板设置
templates:
  variables:
    course_name: ""
    instructor: ""
    date: ""
    tags: []
    
# 日志设置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/process.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# 高级设置
advanced:
  parallel_processing: false  # 是否启用并行处理
  cache_enabled: true  # 是否启用缓存
  cache_dir: "./cache"
  timeout: 300  # API 超时时间（秒）
  retry_count: 3  # API 调用重试次数